<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove=".vs\**" />
    <Compile Remove="DTO\Control\**" />
    <Compile Remove="DTO\Fordward\**" />
    <Compile Remove="DTO\Tactic\**" />
    <EmbeddedResource Remove=".vs\**" />
    <EmbeddedResource Remove="DTO\Control\**" />
    <EmbeddedResource Remove="DTO\Fordward\**" />
    <EmbeddedResource Remove="DTO\Tactic\**" />
    <None Remove=".vs\**" />
    <None Remove="DTO\Control\**" />
    <None Remove="DTO\Fordward\**" />
    <None Remove="DTO\Tactic\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DTO\Defender\SesionDTO.cs" />
    <Compile Remove="DTO\Defender\UsuarioMenuDTO.cs" />
    <Compile Remove="DTO\Lineup\AgenteModelo.cs" />
    <Compile Remove="DTO\Lineup\BodegaModelo.cs" />
    <Compile Remove="DTO\Lineup\ConductorModelo.cs" />
    <Compile Remove="DTO\Lineup\DocumentoDetalleModelo.cs" />
    <Compile Remove="DTO\Lineup\DocumentoModelo.cs" />
    <Compile Remove="DTO\Lineup\DocumentoTipoModelo.cs" />
    <Compile Remove="DTO\Lineup\ListaPrecioModelo.cs" />
    <Compile Remove="DTO\Lineup\MDDocumentoDetallesModelo.cs" />
    <Compile Remove="DTO\Lineup\MDListaPrecioDetallesModelo.cs" />
    <Compile Remove="DTO\Lineup\ProveedorModelo.cs" />
    <Compile Remove="DTO\Lineup\TipoMantenimientoModelo.cs" />
    <Compile Remove="DTO\Lineup\UnidadMedidaModelo.cs" />
    <Compile Remove="DTO\Lineup\VBodegaModelo.cs" />
    <Compile Remove="DTO\Lineup\VDocumentoDetalleModelo.cs" />
    <Compile Remove="DTO\Lineup\VDocumentoModelo.cs" />
    <Compile Remove="DTO\Lineup\VElementoModelo.cs" />
    <Compile Remove="DTO\Lineup\VListaPrecioDetalleModelo.cs" />
    <Compile Remove="DTO\Lineup\VProyectoModelo.cs" />
    <Compile Remove="DTO\MensajeModelo.cs" />
    <Compile Remove="Services\UserService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spherical.Core\Spherical.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\Inventory\" />
  </ItemGroup>

</Project>
