<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.14.0" />
    <PackageReference Include="MudBlazor" Version="8.14.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spherical.Client\Spherical.Client.csproj" />
    <ProjectReference Include="..\Spherical.Core\Spherical.Core.csproj" />
  </ItemGroup>

</Project>
