<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <Compile Remove="Pages\Control\**" />
    <Compile Remove="Pages\Defender\**" />
    <Compile Remove="Pages\Fordward\**" />
    <Compile Remove="Pages\Lineup\**" />
    <Compile Remove="Pages\Tactic\**" />
    <Compile Remove="Services\**" />
    <Content Remove="Data\**" />
    <Content Remove="Pages\Control\**" />
    <Content Remove="Pages\Defender\**" />
    <Content Remove="Pages\Fordward\**" />
    <Content Remove="Pages\Lineup\**" />
    <Content Remove="Pages\Tactic\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Pages\Control\**" />
    <EmbeddedResource Remove="Pages\Defender\**" />
    <EmbeddedResource Remove="Pages\Fordward\**" />
    <EmbeddedResource Remove="Pages\Lineup\**" />
    <EmbeddedResource Remove="Pages\Tactic\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Data\**" />
    <None Remove="Pages\Control\**" />
    <None Remove="Pages\Defender\**" />
    <None Remove="Pages\Fordward\**" />
    <None Remove="Pages\Lineup\**" />
    <None Remove="Pages\Tactic\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.1.1" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\favicon.ico">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\DTO\Inventory\" />
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\plantillas\" />
  </ItemGroup>

</Project>
