<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authentication\**" />
    <Compile Remove="Components\**" />
    <Compile Remove="Data\**" />
    <Compile Remove="Pages\Control\**" />
    <Compile Remove="Pages\Defender\**" />
    <Compile Remove="Pages\Fordward\**" />
    <Compile Remove="Pages\Lineup\**" />
    <Compile Remove="Pages\Tactic\**" />
    <Compile Remove="Services\**" />
    <Content Remove="Authentication\**" />
    <Content Remove="Components\**" />
    <Content Remove="Data\**" />
    <Content Remove="Pages\Control\**" />
    <Content Remove="Pages\Defender\**" />
    <Content Remove="Pages\Fordward\**" />
    <Content Remove="Pages\Lineup\**" />
    <Content Remove="Pages\Tactic\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Authentication\**" />
    <EmbeddedResource Remove="Components\**" />
    <EmbeddedResource Remove="Data\**" />
    <EmbeddedResource Remove="Pages\Control\**" />
    <EmbeddedResource Remove="Pages\Defender\**" />
    <EmbeddedResource Remove="Pages\Fordward\**" />
    <EmbeddedResource Remove="Pages\Lineup\**" />
    <EmbeddedResource Remove="Pages\Tactic\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Authentication\**" />
    <None Remove="Components\**" />
    <None Remove="Data\**" />
    <None Remove="Pages\Control\**" />
    <None Remove="Pages\Defender\**" />
    <None Remove="Pages\Fordward\**" />
    <None Remove="Pages\Lineup\**" />
    <None Remove="Pages\Tactic\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spherical.Blazor\Spherical.Blazor.csproj" />
    <ProjectReference Include="..\Spherical.Client\Spherical.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\favicon.ico">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
  </ItemGroup>

</Project>
