//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creative.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Creative.Recursos.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string EtiquetaActivo {
            get {
                return ResourceManager.GetString("EtiquetaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string EtiquetaAdmin {
            get {
                return ResourceManager.GetString("EtiquetaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        public static string EtiquetaAgenteNombre {
            get {
                return ResourceManager.GetString("EtiquetaAgenteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticipo.
        /// </summary>
        public static string EtiquetaAnticipo {
            get {
                return ResourceManager.GetString("EtiquetaAnticipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string EtiquetaAnulado {
            get {
                return ResourceManager.GetString("EtiquetaAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string EtiquetaApellido {
            get {
                return ResourceManager.GetString("EtiquetaApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido 1.
        /// </summary>
        public static string EtiquetaApellido1 {
            get {
                return ResourceManager.GetString("EtiquetaApellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido 2.
        /// </summary>
        public static string EtiquetaApellido2 {
            get {
                return ResourceManager.GetString("EtiquetaApellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodega Destino.
        /// </summary>
        public static string EtiquetaBodegaDestinoNombre {
            get {
                return ResourceManager.GetString("EtiquetaBodegaDestinoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodega Origen.
        /// </summary>
        public static string EtiquetaBodegaOrigenNombre {
            get {
                return ResourceManager.GetString("EtiquetaBodegaOrigenNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cámara Comercio.
        /// </summary>
        public static string EtiquetaCamaraComercio {
            get {
                return ResourceManager.GetString("EtiquetaCamaraComercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string EtiquetaCantidad {
            get {
                return ResourceManager.GetString("EtiquetaCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Filas.
        /// </summary>
        public static string EtiquetaCantidadFilas {
            get {
                return ResourceManager.GetString("EtiquetaCantidadFilas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta Pagare.
        /// </summary>
        public static string EtiquetaCartaPagare {
            get {
                return ResourceManager.GetString("EtiquetaCartaPagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string EtiquetaCelular {
            get {
                return ResourceManager.GetString("EtiquetaCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string EtiquetaCiudadNombre {
            get {
                return ResourceManager.GetString("EtiquetaCiudadNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string EtiquetaClave {
            get {
                return ResourceManager.GetString("EtiquetaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string EtiquetaClienteNombre {
            get {
                return ResourceManager.GetString("EtiquetaClienteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string EtiquetaCodigo {
            get {
                return ResourceManager.GetString("EtiquetaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        public static string EtiquetaConductor {
            get {
                return ResourceManager.GetString("EtiquetaConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string EtiquetaConsecutivo {
            get {
                return ResourceManager.GetString("EtiquetaConsecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato Alquiler.
        /// </summary>
        public static string EtiquetaContratoAlquiler {
            get {
                return ResourceManager.GetString("EtiquetaContratoAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string EtiquetaCorreo {
            get {
                return ResourceManager.GetString("EtiquetaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depósito.
        /// </summary>
        public static string EtiquetaDeposito {
            get {
                return ResourceManager.GetString("EtiquetaDeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto Alquiler.
        /// </summary>
        public static string EtiquetaDescuentoAlquiler {
            get {
                return ResourceManager.GetString("EtiquetaDescuentoAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto Mantenimiento.
        /// </summary>
        public static string EtiquetaDescuentoMantenimiento {
            get {
                return ResourceManager.GetString("EtiquetaDescuentoMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto Reposicion.
        /// </summary>
        public static string EtiquetaDescuentoReposicion {
            get {
                return ResourceManager.GetString("EtiquetaDescuentoReposicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto Transporte.
        /// </summary>
        public static string EtiquetaDescuentoTransporte {
            get {
                return ResourceManager.GetString("EtiquetaDescuentoTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto Venta.
        /// </summary>
        public static string EtiquetaDescuentoVenta {
            get {
                return ResourceManager.GetString("EtiquetaDescuentoVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despachado Parcial.
        /// </summary>
        public static string EtiquetaDespacho {
            get {
                return ResourceManager.GetString("EtiquetaDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string EtiquetaDireccion {
            get {
                return ResourceManager.GetString("EtiquetaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string EtiquetaDocumentoTipoNombre {
            get {
                return ResourceManager.GetString("EtiquetaDocumentoTipoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento.
        /// </summary>
        public static string EtiquetaElementoNombre {
            get {
                return ResourceManager.GetString("EtiquetaElementoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo Adecuado.
        /// </summary>
        public static string EtiquetaEquipoAdecuado {
            get {
                return ResourceManager.GetString("EtiquetaEquipoAdecuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es Sistema.
        /// </summary>
        public static string EtiquetaEsSistema {
            get {
                return ResourceManager.GetString("EtiquetaEsSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string EtiquetaFecha {
            get {
                return ResourceManager.GetString("EtiquetaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Entrega.
        /// </summary>
        public static string EtiquetaFechaEntrega {
            get {
                return ResourceManager.GetString("EtiquetaFechaEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pedido.
        /// </summary>
        public static string EtiquetaFechaPedido {
            get {
                return ResourceManager.GetString("EtiquetaFechaPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Sistema.
        /// </summary>
        public static string EtiquetaFechaSistema {
            get {
                return ResourceManager.GetString("EtiquetaFechaSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma Contacto.
        /// </summary>
        public static string EtiquetaFormaContacto {
            get {
                return ResourceManager.GetString("EtiquetaFormaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto Copia Cédula.
        /// </summary>
        public static string EtiquetaFotoCopiaCedula {
            get {
                return ResourceManager.GetString("EtiquetaFotoCopiaCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto Copia Nit.
        /// </summary>
        public static string EtiquetaFotoCopiaNit {
            get {
                return ResourceManager.GetString("EtiquetaFotoCopiaNit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garantías Condiciones.
        /// </summary>
        public static string EtiquetaGarantiasCondiciones {
            get {
                return ResourceManager.GetString("EtiquetaGarantiasCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Elemento.
        /// </summary>
        public static string EtiquetaGrupoElementoNombre {
            get {
                return ResourceManager.GetString("EtiquetaGrupoElementoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string EtiquetaId {
            get {
                return ResourceManager.GetString("EtiquetaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string EtiquetaIdentificacion {
            get {
                return ResourceManager.GetString("EtiquetaIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación Responsable.
        /// </summary>
        public static string EtiquetaIdentificacionResponsable {
            get {
                return ResourceManager.GetString("EtiquetaIdentificacionResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información BD.
        /// </summary>
        public static string EtiquetaInformacionBD {
            get {
                return ResourceManager.GetString("EtiquetaInformacionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciales.
        /// </summary>
        public static string EtiquetaIniciales {
            get {
                return ResourceManager.GetString("EtiquetaIniciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letra Cambio.
        /// </summary>
        public static string EtiquetaLetraCambio {
            get {
                return ResourceManager.GetString("EtiquetaLetraCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Precio.
        /// </summary>
        public static string EtiquetaListaPrecioNombre {
            get {
                return ResourceManager.GetString("EtiquetaListaPrecioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mt2.
        /// </summary>
        public static string EtiquetaMt2 {
            get {
                return ResourceManager.GetString("EtiquetaMt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre 1.
        /// </summary>
        public static string EtiquetaNombre1 {
            get {
                return ResourceManager.GetString("EtiquetaNombre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre 2.
        /// </summary>
        public static string EtiquetaNombre2 {
            get {
                return ResourceManager.GetString("EtiquetaNombre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Responsable.
        /// </summary>
        public static string EtiquetaNombreResponsable {
            get {
                return ResourceManager.GetString("EtiquetaNombreResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string EtiquetaNumero {
            get {
                return ResourceManager.GetString("EtiquetaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string EtiquetaObservacion {
            get {
                return ResourceManager.GetString("EtiquetaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación.
        /// </summary>
        public static string EtiquetaOperacion {
            get {
                return ResourceManager.GetString("EtiquetaOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagare.
        /// </summary>
        public static string EtiquetaPagare {
            get {
                return ResourceManager.GetString("EtiquetaPagare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona Juridica.
        /// </summary>
        public static string EtiquetaPersonaJuridica {
            get {
                return ResourceManager.GetString("EtiquetaPersonaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona Natural.
        /// </summary>
        public static string EtiquetaPersonaNatural {
            get {
                return ResourceManager.GetString("EtiquetaPersonaNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string EtiquetaPeso {
            get {
                return ResourceManager.GetString("EtiquetaPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Equipo.
        /// </summary>
        public static string EtiquetaPesoEquipo {
            get {
                return ResourceManager.GetString("EtiquetaPesoEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa.
        /// </summary>
        public static string EtiquetaPlaca {
            get {
                return ResourceManager.GetString("EtiquetaPlaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Agente.
        /// </summary>
        public static string EtiquetaPorcentajeAgente {
            get {
                return ResourceManager.GetString("EtiquetaPorcentajeAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Alquiler.
        /// </summary>
        public static string EtiquetaPrecioAlquiler {
            get {
                return ResourceManager.GetString("EtiquetaPrecioAlquiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Perdida.
        /// </summary>
        public static string EtiquetaPrecioPerdida {
            get {
                return ResourceManager.GetString("EtiquetaPrecioPerdida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Venta.
        /// </summary>
        public static string EtiquetaPrecioVenta {
            get {
                return ResourceManager.GetString("EtiquetaPrecioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string EtiquetaProveedorNombre {
            get {
                return ResourceManager.GetString("EtiquetaProveedorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string EtiquetaProyectoNombre {
            get {
                return ResourceManager.GetString("EtiquetaProyectoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencia.
        /// </summary>
        public static string EtiquetaReferencia {
            get {
                return ResourceManager.GetString("EtiquetaReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string EtiquetaRolNombre {
            get {
                return ResourceManager.GetString("EtiquetaRolNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotacion.
        /// </summary>
        public static string EtiquetaRotacion {
            get {
                return ResourceManager.GetString("EtiquetaRotacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema Medida.
        /// </summary>
        public static string EtiquetaSistemaMedida {
            get {
                return ResourceManager.GetString("EtiquetaSistemaMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string EtiquetaTelefono {
            get {
                return ResourceManager.GetString("EtiquetaTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. Responsable.
        /// </summary>
        public static string EtiquetaTelResponsable {
            get {
                return ResourceManager.GetString("EtiquetaTelResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string EtiquetaTipo {
            get {
                return ResourceManager.GetString("EtiquetaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte.
        /// </summary>
        public static string EtiquetaTransporte {
            get {
                return ResourceManager.GetString("EtiquetaTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Medida.
        /// </summary>
        public static string EtiquetaUnidadMedidaNombre {
            get {
                return ResourceManager.GetString("EtiquetaUnidadMedidaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string EtiquetaUsuario {
            get {
                return ResourceManager.GetString("EtiquetaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string EtiquetaValor {
            get {
                return ResourceManager.GetString("EtiquetaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Equipo.
        /// </summary>
        public static string EtiquetaValorEquipo {
            get {
                return ResourceManager.GetString("EtiquetaValorEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Transporte.
        /// </summary>
        public static string EtiquetaValorTransporte {
            get {
                return ResourceManager.GetString("EtiquetaValorTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión.
        /// </summary>
        public static string EtiquetaVersion {
            get {
                return ResourceManager.GetString("EtiquetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Requerido.
        /// </summary>
        public static string MensajeRequerido {
            get {
                return ResourceManager.GetString("MensajeRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo no puede tener más de {0} caracteres..
        /// </summary>
        public static string MensajeTamanoMaximo {
            get {
                return ResourceManager.GetString("MensajeTamanoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes.
        /// </summary>
        public static string TituloAgenteListar {
            get {
                return ResourceManager.GetString("TituloAgenteListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Agente.
        /// </summary>
        public static string TituloBloqueAgenteConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueAgenteConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Agente.
        /// </summary>
        public static string TituloBloqueAgenteInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueAgenteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Agente.
        /// </summary>
        public static string TituloBloqueAgenteModificar {
            get {
                return ResourceManager.GetString("TituloBloqueAgenteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Bodega.
        /// </summary>
        public static string TituloBloqueBodegaConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueBodegaConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Bodega.
        /// </summary>
        public static string TituloBloqueBodegaInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueBodegaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Bodega.
        /// </summary>
        public static string TituloBloqueBodegaModificar {
            get {
                return ResourceManager.GetString("TituloBloqueBodegaModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Ciudad.
        /// </summary>
        public static string TituloBloqueCiudadConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueCiudadConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Ciudad.
        /// </summary>
        public static string TituloBloqueCiudadInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueCiudadInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Ciudad.
        /// </summary>
        public static string TituloBloqueCiudadModificar {
            get {
                return ResourceManager.GetString("TituloBloqueCiudadModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Cliente.
        /// </summary>
        public static string TituloBloqueClienteConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueClienteConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Cliente.
        /// </summary>
        public static string TituloBloqueClienteInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueClienteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Cliente.
        /// </summary>
        public static string TituloBloqueClienteModificar {
            get {
                return ResourceManager.GetString("TituloBloqueClienteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Conductor.
        /// </summary>
        public static string TituloBloqueConductorConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueConductorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Conductor.
        /// </summary>
        public static string TituloBloqueConductorInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueConductorInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Conductor .
        /// </summary>
        public static string TituloBloqueConductorModificar {
            get {
                return ResourceManager.GetString("TituloBloqueConductorModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Contrato.
        /// </summary>
        public static string TituloBloqueContratoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueContratoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Documento.
        /// </summary>
        public static string TituloBloqueDocumentoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Documento .
        /// </summary>
        public static string TituloBloqueDocumentoDetalleConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoDetalleConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Documento.
        /// </summary>
        public static string TituloBloqueDocumentoDetalleModificar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoDetalleModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insetar Documento.
        /// </summary>
        public static string TituloBloqueDocumentoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Documento.
        /// </summary>
        public static string TituloBloqueDocumentoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Tipo Documento.
        /// </summary>
        public static string TituloBloqueDocumentoTipoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoTipoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Tipo Documento.
        /// </summary>
        public static string TituloBloqueDocumentoTipoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoTipoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Tipo Documento.
        /// </summary>
        public static string TituloBloqueDocumentoTipoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueDocumentoTipoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Elemento.
        /// </summary>
        public static string TituloBloqueElementoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueElementoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Elemento.
        /// </summary>
        public static string TituloBloqueElementoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueElementoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Elemento.
        /// </summary>
        public static string TituloBloqueElementoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueElementoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Grupo de Elementos.
        /// </summary>
        public static string TituloBloqueGrupoElementoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueGrupoElementoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Grupo de Elementos.
        /// </summary>
        public static string TituloBloqueGrupoElementoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueGrupoElementoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Grupo de Elementos.
        /// </summary>
        public static string TituloBloqueGrupoElementoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueGrupoElementoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Lista Precios.
        /// </summary>
        public static string TituloBloqueListaPrecioConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueListaPrecioConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insetar Lista Precios.
        /// </summary>
        public static string TituloBloqueListaPrecioInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueListaPrecioInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Lista Precios.
        /// </summary>
        public static string TituloBloqueListaPrecioModificar {
            get {
                return ResourceManager.GetString("TituloBloqueListaPrecioModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Parametro.
        /// </summary>
        public static string TituloBloqueParametroConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueParametroConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insetar Parrametro.
        /// </summary>
        public static string TituloBloqueParametroInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueParametroInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Parametro.
        /// </summary>
        public static string TituloBloqueParametroModificar {
            get {
                return ResourceManager.GetString("TituloBloqueParametroModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Proveedor.
        /// </summary>
        public static string TituloBloqueProveedorConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueProveedorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Proveedor.
        /// </summary>
        public static string TituloBloqueProveedorInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueProveedorInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Proveedor.
        /// </summary>
        public static string TituloBloqueProveedorModificar {
            get {
                return ResourceManager.GetString("TituloBloqueProveedorModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Proyecto.
        /// </summary>
        public static string TituloBloqueProyectoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueProyectoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Proyecto.
        /// </summary>
        public static string TituloBloqueProyectoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueProyectoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Proyecto.
        /// </summary>
        public static string TituloBloqueProyectoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueProyectoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insetar Remisión.
        /// </summary>
        public static string TituloBloqueRemisionInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueRemisionInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Tipo Mantenimiento.
        /// </summary>
        public static string TituloBloqueTipoMantenimientoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoMantenimientoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Tipo Mantenimiento.
        /// </summary>
        public static string TituloBloqueTipoMantenimientoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoMantenimientoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Tipo Mantenimiento.
        /// </summary>
        public static string TituloBloqueTipoMantenimientoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoMantenimientoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Unidad Medida.
        /// </summary>
        public static string TituloBloqueUnidadMedidaConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueUnidadMedidaConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar Unidad Medida.
        /// </summary>
        public static string TituloBloqueUnidadMedidaInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueUnidadMedidaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Unidad Medida.
        /// </summary>
        public static string TituloBloqueUnidadMedidaModificar {
            get {
                return ResourceManager.GetString("TituloBloqueUnidadMedidaModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodegas .
        /// </summary>
        public static string TituloBodegaListar {
            get {
                return ResourceManager.GetString("TituloBodegaListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudades.
        /// </summary>
        public static string TituloCiudadListar {
            get {
                return ResourceManager.GetString("TituloCiudadListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string TituloClienteListar {
            get {
                return ResourceManager.GetString("TituloClienteListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductores.
        /// </summary>
        public static string TituloConductorListar {
            get {
                return ResourceManager.GetString("TituloConductorListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listas de Documentos.
        /// </summary>
        public static string TituloDocumentoListar {
            get {
                return ResourceManager.GetString("TituloDocumentoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos Documentos.
        /// </summary>
        public static string TituloDocumentoTipoListar {
            get {
                return ResourceManager.GetString("TituloDocumentoTipoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementos.
        /// </summary>
        public static string TituloElementoListar {
            get {
                return ResourceManager.GetString("TituloElementoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de Elementos.
        /// </summary>
        public static string TituloGrupoElementoListar {
            get {
                return ResourceManager.GetString("TituloGrupoElementoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listas de Precios.
        /// </summary>
        public static string TituloListaPrecioListar {
            get {
                return ResourceManager.GetString("TituloListaPrecioListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros.
        /// </summary>
        public static string TituloParametroListar {
            get {
                return ResourceManager.GetString("TituloParametroListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string TituloProveedorListar {
            get {
                return ResourceManager.GetString("TituloProveedorListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string TituloProyectoListar {
            get {
                return ResourceManager.GetString("TituloProyectoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimientos.
        /// </summary>
        public static string TituloProyectoPlanillaListar {
            get {
                return ResourceManager.GetString("TituloProyectoPlanillaListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos Mantenimientos.
        /// </summary>
        public static string TituloTipoMantenimientoListar {
            get {
                return ResourceManager.GetString("TituloTipoMantenimientoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de Medida.
        /// </summary>
        public static string TituloUnidadMedidaListar {
            get {
                return ResourceManager.GetString("TituloUnidadMedidaListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Login.
        /// </summary>
        public static string TituloUsuarioLogin {
            get {
                return ResourceManager.GetString("TituloUsuarioLogin", resourceCulture);
            }
        }
    }
}
